### ISSUE TITLE
Automatically assigning protonation states to residues according to an excel file 

### ISSUE THREAD

**Issue by wintermute221** [andymlau/ChargeRoulette#1]
Hi!

Your work is really interesting! I was just thinking if it's possible to be applied in my research. 

Currently I'm trying to assigning different protonation states to my protein in Gromacs so as to mimic different pHs in the real world. I've already generated an excel file containing the protonation states I desire for the six protein residues (lys, glu, his, arg, asp, gln) with the [pdb2pqr server](https://server.poissonboltzmann.org/pdb2pqr) and just as you said, every time it's tedious to set them up in Gromacs. So I was just wondering if your script is able to read an excel file and then assign the protonation states accordingly?

Thank you very much.

**Comment by andymlau** [comment]
Hi, 

Sorry for the long wait - I didn't get a notification for your message and I've just accidentally stumbled upon it. 

If you already have a list of residues, then this can be passed to ChargeRoulette as a custom assignment schedule (check [here](https://github.com/andymlau/ChargeRoulette#using-a-custom-assignment-schedule)). 

In that file, each row should be a set of charges that you wish to assign through pdb2gmx. As you will notice, currently only Lys, Arg and His residues can be customised, so [__auto_assign.exp](https://github.com/andymlau/ChargeRoulette/blob/bf2098f4322e8dbecc15dc2f83bd5f82a3f62a2c/scripts/__auto_assign.exp) will also need to be edited to handle assignments for Asp, Glu, etc. 

Hope this helps!

**Comment by wintermute221** [comment]
No worries at all! Thank you for the answer - I will have a go.
